### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kouzhudong** [quarkslab/qb-sync#4]
C:\Program Files\IDA 7.2\plugins\SyncPlugin.py: Traceback (most recent call last):
  File "C:\Program Files\IDA 7.2\python\ida_idaapi.py", line 572, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files/IDA 7.2/plugins/SyncPlugin.py", line 59, in <module>
    sys.exit(0)
SystemExit: 0

**Comment by kouzhudong** [comment]
if sys.platform == 'win32':
    PYTHON_BIN = 'python.exe'
    PYTHON_PATH = os.path.normpath("C:\\Python27")

elif sys.platform.startswith('linux') or sys.platform == 'darwin':
    PYTHON_BIN = 'python'
    PYTHON_PATH = os.path.normpath("/usr/bin")

else:
    print "[-] please fix PYTHON_PATH & PYTHON_BIN values, %s platform currently unknown" % sys.platform
    sys.exit(0)

if not os.path.exists(os.path.join(PYTHON_PATH, PYTHON_BIN)):
    print "[-] please fix PYTHON_PATH value"
    sys.exit(0)

**Comment by kouzhudong** [comment]
C:\Program Files\IDA 7.2\plugins\SyncPlugin.py: Traceback (most recent call last):
  File "C:\Program Files\IDA 7.2\python\ida_idaapi.py", line 572, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files/IDA 7.2/plugins/SyncPlugin.py", line 72, in <module>
    sys.exit(0)
SystemExit: 0

**Comment by kouzhudong** [comment]
太挫了，太久了。

**Comment by kouzhudong** [comment]
想了想，不是改变环境满足你代码的需求，而是改变代码以适合我的环境。
